# Generated by Django 5.1.4 on 2025-04-05 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insc', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('noti', models.BooleanField(default=False)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('andamento', models.CharField(choices=[('aguardando prazo', 'Aguardando Prazo'), ('resolvido', 'Resolvido'), ('vencido', 'Vencido')], default='aguardando prazo', max_length=20)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local.local')),
            ],
        ),
    ]
