# Generated by Django 5.1.4 on 2025-04-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0003_local_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='status',
            field=models.CharField(choices=[('fogo', 'Fogo'), ('lixo', 'Lixo'), ('barulho', 'Barulho'), ('ambulante', 'Ambulante'), ('terreno sujo', 'Terreno Sujo'), ('costrução comprometida', 'Construção Comprometida'), ('invazão de plantas', 'Invazão de Plantas'), ('outro', 'Outro')], max_length=200),
        ),
    ]
