# Generated by Django 5.1.4 on 2024-12-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0006_alter_local_insc'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='endereco',
            field=models.TextField(default='Endereço não informado'),
            preserve_default=False,
        ),
    ]
