# Generated by Django 5.1.4 on 2024-12-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0007_local_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='endereco',
            field=models.CharField(max_length=50),
        ),
    ]
