# Generated by Django 5.1.4 on 2025-02-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0008_alter_local_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='status',
            field=models.CharField(choices=[('fogo', 'Fogo'), ('lixo', 'Lixo'), ('ambulante', 'Ambulante'), ('null', 'Sem status')], default='null', max_length=10),
        ),
    ]
