# Generated by Django 5.1.4 on 2025-03-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0009_alter_ocorrencia_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='status',
            field=models.CharField(choices=[('fogo', 'Fogo'), ('lixo', 'Lixo'), ('ambulante', 'Ambulante'), ('terreno sujo', 'Terreno Sujo'), ('construção comprometida', 'Construção Comprometida '), ('invasão de plantas', 'Invasão de Plantas'), ('null', 'Sem status')], default='null', max_length=28),
        ),
    ]
